apiVersion: v1;
kind: Service
metadata:
   name: redis
   labels:
    name: redis-pod
    app: demo-voting-app
spec: 
    ports:
    - targetPort: 6379
      port: 6379
    selector:
       app: redis-pod
       type: demo-voting-app